# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

name: 'mlflowserver-azure-release'
trigger:
  branches:
    include:
    - releases/*
    exclude:
    - master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerId: 'devlace'
  imageName: 'mlflowserver-azure'

steps:
- displayName: 'docker build'
  script: docker build -f mlflow-tracking-docker/Dockerfile -t $(dockerId)/$(imageName):$(Build.SourceBranch) .
- displayName: 'docker push'
  script: |
    docker login -u $(dockerId) -p $(dockerPswd)
    docker push $(dockerId)/$(imageName):$(Build.SourceBranch)